version: '2'
services:
  preact:
    build: ./preact
    ports:
      - "5000:5000"
    restart: always
  api:
    build: ./api
  dynamo:
    image: cnadiminti/dynamodb-local:latest
    volumes:
      - ./dynamo:/dynamodb_local_db
    ports:
      - "8000:8000"
    restart: always
networks:
  panda-net:
    driver: bridge
